#!/bin/bash
set -e

search() {
    # give focus to the last file selected
    file_to_edit=$(fzf --preview="cat {}" --preview-window=right:70%:wrap)
    if [ -n "$file_to_edit" ]; then
        # edit in vim
        vim "$file_to_edit"
    fi
}

# working directory
if [ -d "$HOME/notes" ]; then
    cd "$HOME/notes"
fi

if [ -n "$1" ]; then
    # use all args to build file name
    IFS='_'
    file_to_edit="${*}.md"
    IFS=' '
    vim "$file_to_edit"
else
    # if no args trigger the search
    search
fi
